"""Copy the ways-of-working notes from an Obsidian vault into docs/.

The vault is the source of truth; docs/ is generated from it. Run:

    uv run invoke sync --vault ~/path/to/vault
"""

import argparse
import re
import shutil
from pathlib import Path, PurePosixPath

SOURCE = Path("knowledge-base/ways-of-working")
DOCS = Path(__file__).parent.parent / "docs"

# Notes that move to a different place on the site; everything else keeps its
# folder and gets a slugified file name.
RENAMES = {
    "Engineering Excellence.md": "index.md",
    "Data Team - Ways of working.md": "ways-of-working.md",
    "Security and compliance.md": "security/security-and-compliance.md",
}

# Hand-written pages that live only in this repository.
HAND_WRITTEN = {"in-practice.md", "assets", "stylesheets"}

HEADER = (
    "<!-- Generated by scripts/sync.py from the source notes."
    " Edit them, not this file. -->\n\n"
)

WIKILINK = re.compile(r"\[\[([^\]|]+)(?:\|([^\]]+))?\]\]")
BREADCRUMB = re.compile(r"^\s*[←↑→]\s*")
TAGS_SECTION = re.compile(r"^## Tags\n.*?(?=^## |^---|\Z)", re.MULTILINE | re.DOTALL)


def slugify(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def destination(relative: PurePosixPath) -> PurePosixPath:
    if relative.as_posix() in RENAMES:
        return PurePosixPath(RENAMES[relative.as_posix()])
    return relative.parent / f"{slugify(relative.stem)}.md"


def relative_link(source: PurePosixPath, target: PurePosixPath) -> str:
    depth = len(source.parent.parts)
    return "/".join([".."] * depth + [target.as_posix()])


def convert(text: str, page: PurePosixPath, pages: dict[str, PurePosixPath]) -> str:
    """Turn wikilinks into relative Markdown links and drop vault-only content.

    ``pages`` maps note titles to their site paths. Lines that only hold a
    breadcrumb to a note outside the handbook are removed; other unresolved
    links become plain text.
    """
    lines = []
    for line in TAGS_SECTION.sub("", text).splitlines():
        links = WIKILINK.findall(line)
        unresolved = [t for t, _ in links if PurePosixPath(t).name not in pages]
        if BREADCRUMB.match(line) and links and len(unresolved) == len(links):
            continue
        lines.append(line.rstrip())

    def replace(match: re.Match[str]) -> str:
        target, alias = match.group(1), match.group(2)
        title = PurePosixPath(target).name
        label = alias or title
        if title not in pages:
            return label
        return f"[{label}]({relative_link(page, pages[title])})"

    body = WIKILINK.sub(replace, "\n".join(lines)).strip()
    body = re.sub(r"\n{3,}", "\n\n", body)
    body = re.sub(r"^---\n\n(?:---\n\n)+", "---\n\n", body, flags=re.MULTILINE)
    return HEADER + body + "\n"


def sync(vault: Path) -> list[PurePosixPath]:
    source = vault / SOURCE
    notes = sorted(source.rglob("*.md"))
    if not notes:
        raise SystemExit(f"No notes found in {source}")
    relatives = [PurePosixPath(n.relative_to(source).as_posix()) for n in notes]
    pages = {r.stem: destination(r) for r in relatives}

    for path in DOCS.iterdir():
        if path.name in HAND_WRITTEN or path.name.startswith("."):
            continue
        shutil.rmtree(path) if path.is_dir() else path.unlink()

    for note, relative in zip(notes, relatives, strict=True):
        page = pages[relative.stem]
        target = DOCS / page
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(convert(note.read_text(), page, pages))
    return sorted(pages.values())


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--vault", type=Path, required=True)
    written = sync(parser.parse_args().vault.expanduser())
    print(f"Synced {len(written)} pages into {DOCS}")


if __name__ == "__main__":
    main()
